export const videoArray = [
  {
    id: 18,
    img: new URL("../img/video_pelmeni.jpg", import.meta.url),
    link: "sleryK4X4S8",
    heading: "Пельмені",
    subheading: "ІДЕАЛЬНЕ тісто + соковита начинка❗Домашні пельмені ❗",
    category: "1, 2",
  },
  {
    id: 17,
    img: new URL("../img/video_rulet.jpg", import.meta.url),
    link: "mB0RmAnJuXU",
    heading: "Фаршировані Стегенця",
    subheading: "🍗Бюджетно та по-Святковому 🎄",
    category: "2",
  },
  {
    id: 16,
    img: new URL("../img/video_hinkali.jpg", import.meta.url),
    link: "cxQhBzr7Cvk",
    heading: "🔴ХІНКАЛІ на вашій кухні",
    subheading: "Грузинська смакота з Українським акцентом💛💙",
    category: "1, 2",
  },
  {
    id: 15,
    img: new URL("../img/video_soup.jpg", import.meta.url),
    link: "f00Nm0q9Q5w",
    heading: "🧡Найяскравіший СУП цієї ОСЕНІ",
    subheading: "🍂/ pumpkin soup🥘",
    category: "3",
  },
  {
    id: 14,
    img: new URL("../img/video_shtruli.jpg", import.meta.url),
    link: "VwI54d-rThQ",
    heading: "Штрулі",
    subheading: "НАПІВФАБРИКАТИ для особливого випадку 🥟Як усе встигнути 👨‍🍳",
    category: "1, 2",
  },
  {
    id: 13,
    img: new URL("../img/video_pancakes.jpg", import.meta.url),
    link: "Bz5lxckxeoo",
    heading: "ТОП 5 Найкрасивіших булочок",
    subheading: "🥨Проста та зручна формовка",
    category: "4, 5",
  },
  {
    id: 12,
    img: new URL("../img/video_holubzi.jpg", import.meta.url),
    link: "VVMcesPAWiM",
    heading: "🔴ГОЛУБЦІ",
    subheading:
      "Всі тонкощі приготування та ТОП 3 способи закрутки (швидко і просто)❗",
    category: "1, 2",
  },
  {
    id: 11,
    img: new URL("../img/lasui.webp", import.meta.url),
    link: "k412HWe9vFQ",
    heading: "Ласуй, та Не Думай про Калорії ❗",
    subheading: "Корисний Перекус, що можна взяти з собою в дорогу",
    category: "5",
  },
  {
    id: 10,
    img: new URL("../img/hachapuri.webp", import.meta.url),
    link: "WtE1Et_gM8Y",
    heading: "ХАЧАПУРІ",
    subheading: "Експрес ХАЧАПУРІ за 10 хвилин🍕🥮",
    category: "2, 4",
  },
  {
    id: 9,
    img: new URL("../img/hearts.webp", import.meta.url),
    link: "TZiPAKqxioY",
    heading: "🔴ТОП 3 рецепти як смачно приготувати курячі сердечка",
    subheading: "НИЗЬКОКАЛОРІЙНІША частина курки.🍗",
    category: "2",
  },
  {
    id: 8,
    img: new URL("../img/hen.jpg", import.meta.url),
    link: "0mqnbl613uM",
    heading: "Курячий рулет з Клюквою🍒",
    subheading: "Неймовірна СМАКОТА!",
    category: "2",
  },
  {
    id: 7,
    img: new URL("../img/easter.webp", import.meta.url),
    link: "dGJ51V5OPy0",
    heading: "Привітання з ВЕЛИКОДНЕМ!",
    subheading: "ХРИСТОС Воскрес!",
    category: "7",
  },
  {
    id: 6,
    img: new URL("../img/salads.webp", import.meta.url),
    link: "XrwUxcr-RNI",
    heading: "Два СУПЕР-САЛАТИ за 5 хвилин 🥗",
    subheading: "для жіночої КРАСИ та ЗДОРОВ'Я. 🥕🍏🥬",
    category: "6",
  },
  {
    id: 5,
    img: new URL("../img/vareniki2.webp", import.meta.url),
    link: "HF2dXaUxVnw",
    heading: "ТОП 3 начинки для ВАРЕНИКІВ",
    subheading: "ТІСТО, що не розварюється🥟🥟🥟",
    category: "1, 2",
  },
  {
    id: 4,
    img: new URL("../img/beat.webp", import.meta.url),
    link: "IHL9qLNiceA",
    heading: "Експрес - ВІДБИВНІ без Смаження на сковороді",
    subheading: "ШВИДКО та ЕКОНОМНО🥩",
    category: "2",
  },
  {
    id: 3,
    img: new URL("../img/hrecha.webp", import.meta.url),
    link: "6E04A_tvnEw",
    heading: "Гречана СМАКОТА з картопляними Кльоцками🥣🥔",
    subheading: "Гречаний суп із кльоцками",
    category: "3",
  },
  {
    id: 2,
    img: new URL("../img/citrus.jpg", import.meta.url),
    link: "P0_DtB_GXuQ",
    heading: "🍊🍋Цитрусові цукати",
    subheading: "випічка на ВЕЛИКДЕНЬ 🍊🍋",
    category: "5",
  },
  {
    id: 1,
    img: new URL("../img/freeze.webp", import.meta.url),
    link: "ZWA_FzCjnI0",
    heading: "ОБЗОР та ВІДГУК на морозильну камеру Vestfrost CMF144W",
    subheading: "Чесний відгук",
    category: "7",
  },
  {
    id: 19,
    img: new URL("../img/video_buters.jpg", import.meta.url),
    link: "5pKsJYTyYj0",
    heading: "🔴ТОП 3 незвичайних закусок зі звичайного Оселедця ❗",
    subheading: "ЩОСЬ НОВЕНЬКЕ на святковий стіл🎄 ❗",
    category: "7",
  },

  {
    id: 20,
    img: new URL("../img/vareniki.webp", import.meta.url),
    link: "_H80tr01h7g",
    heading: "🔴ТОП 3 Способи 'Як защипнути вареники'",
    subheading: "🥟 Фігурне ліплення ВАРЕНИКІВ",
    category: "1, 2",
  },
  {
    id: 21,
    img: new URL("../img/benderyky.webp", import.meta.url),
    link: "-7nlh0Mowc0",
    heading: "Українські БЕНДЕРИКИ🥞 ",
    subheading: "Смачні , Ситні та Бюджетні 💰",
    category: "1, 2",
  },
  // {
  //   id: 10,
  //   img: "",
  //   link: "",
  //   heading: "",
  //   subheading: "",
  //   category: "",
  // },
  // {
  //   id: 10,
  //   img: "",
  //   link: "",
  //   heading: "",
  //   subheading: "",
  //   category: "",
  // },
  // {
  //   id: 10,
  //   img: "",
  //   link: "",
  //   heading: "",
  //   subheading: "",
  //   category: "",
  // },
  // {
  //   id: 10,
  //   img: "",
  //   link: "",
  //   heading: "",
  //   subheading: "",
  //   category: "",
  // },
  // {
  //   id: 10,
  //   img: "",
  //   link: "",
  //   heading: "",
  //   subheading: "",
  //   category: "",
  // },
  // {
  //   id: 10,
  //   img: "",
  //   link: "",
  //   heading: "",
  //   subheading: "",
  //   category: "",
  // },
];
