export const videoArray = [
  {
    id: 18,
    img: new URL("../img/video_pelmeni.jpg", import.meta.url),
    link: "https://www.youtube.com/embed/sleryK4X4S8",
    heading: "Пельмені",
    subheading: "ІДЕАЛЬНЕ тісто + соковита начинка❗Домашні пельмені ❗",
    category: "1, 2",
  },
  {
    id: 17,
    img: new URL("../img/video_rulet.jpg", import.meta.url),
    link: "https://www.youtube.com/embed/mB0RmAnJuXU",
    heading: "Фаршировані Стегенця",
    subheading: "🍗Бюджетно та по-Святковому 🎄",
    category: "2",
  },
  {
    id: 16,
    img: new URL("../img/video_hinkali.jpg", import.meta.url),
    link: "https://www.youtube.com/embed/cxQhBzr7Cvk",
    heading: "🔴ХІНКАЛІ на вашій кухні",
    subheading: "Грузинська смакота з Українським акцентом💛💙",
    category: "1, 2",
  },
  {
    id: 15,
    img: new URL("../img/video_soup.jpg", import.meta.url),
    link: "https://www.youtube.com/embed/f00Nm0q9Q5w",
    heading: "🧡Найяскравіший СУП цієї ОСЕНІ",
    subheading: "🍂/ pumpkin soup🥘",
    category: "3",
  },
  {
    id: 14,
    img: new URL("../img/video_shtruli.jpg", import.meta.url),
    link: "https://www.youtube.com/embed/VwI54d-rThQ",
    heading: "Штрулі",
    subheading: "НАПІВФАБРИКАТИ для особливого випадку 🥟Як усе встигнути 👨‍🍳",
    category: "1, 2",
  },
  {
    id: 13,
    img: new URL("../img/video_pancakes.jpg", import.meta.url),
    link: "https://www.youtube.com/embed/Bz5lxckxeoo",
    heading: "ТОП 5 Найкрасивіших булочок",
    subheading: "🥨Проста та зручна формовка",
    category: "4, 5",
  },
  {
    id: 12,
    img: new URL("../img/video_holubzi.jpg", import.meta.url),
    link: "https://www.youtube.com/embed/VVMcesPAWiM",
    heading: "🔴ГОЛУБЦІ",
    subheading:
      "Всі тонкощі приготування та ТОП 3 способи закрутки (швидко і просто)❗",
    category: "1, 2",
  },
  {
    id: 11,
    img: "https://i9.ytimg.com/vi_webp/k412HWe9vFQ/maxresdefault.webp?v=62cb28c2&sqp=COia9ZsG&rs=AOn4CLDWeaakS6ojCqfHzip4r1Z-Gc2_Kg",
    link: "https://www.youtube.com/embed/k412HWe9vFQ",
    heading: "Ласуй, та Не Думай про Калорії ❗",
    subheading: "Корисний Перекус, що можна взяти з собою в дорогу",
    category: "5",
  },
  {
    id: 10,
    img: "https://i9.ytimg.com/vi_webp/WtE1Et_gM8Y/maxresdefault.webp?v=629265c2&sqp=CJSd9ZsG&rs=AOn4CLDoJSYkydRtFdN5g9U7GtjHCwiGbA",
    link: "https://www.youtube.com/embed/WtE1Et_gM8Y",
    heading: "ХАЧАПУРІ",
    subheading: "Експрес ХАЧАПУРІ за 10 хвилин🍕🥮",
    category: "2, 4",
  },
  {
    id: 9,
    img: "https://i9.ytimg.com/vi_webp/TZiPAKqxioY/maxresdefault.webp?v=627c2650&sqp=CMCf9ZsG&rs=AOn4CLCja8CddqHkJeE4wUH86QDtyC7YKQ",
    link: "https://www.youtube.com/embed/TZiPAKqxioY",
    heading: "🔴ТОП 3 рецепти як смачно приготувати курячі сердечка",
    subheading: "НИЗЬКОКАЛОРІЙНІША частина курки.🍗",
    category: "2",
  },
  {
    id: 8,
    img: "https://i9.ytimg.com/vi/0mqnbl613uM/maxresdefault.jpg?v=626ed71e&sqp=CMCf9ZsG&rs=AOn4CLCrBrCRlHEPGjVYBshqFp3M76gBeg",
    link: "https://www.youtube.com/embed/0mqnbl613uM",
    heading: "Курячий рулет з Клюквою🍒",
    subheading: "Неймовірна СМАКОТА!",
    category: "2",
  },
  {
    id: 7,
    img: "https://i9.ytimg.com/vi_webp/dGJ51V5OPy0/maxresdefault.webp?v=6262ba38&sqp=CMCf9ZsG&rs=AOn4CLBwfRUL7PH3dOys3D807aV6Wp2ldA",
    link: "https://www.youtube.com/embed/dGJ51V5OPy0",
    heading: "Привітання з ВЕЛИКОДНЕМ!",
    subheading: "ХРИСТОС Воскрес!",
    category: "7",
  },
  {
    id: 6,
    img: "https://i9.ytimg.com/vi_webp/XrwUxcr-RNI/maxresdefault.webp?v=625e847a&sqp=CMCf9ZsG&rs=AOn4CLBS-GTkSVQje7aFfzwzGFzeCVKHAA",
    link: "https://www.youtube.com/embed/XrwUxcr-RNI",
    heading: "Два СУПЕР-САЛАТИ за 5 хвилин 🥗",
    subheading: "для жіночої КРАСИ та ЗДОРОВ'Я. 🥕🍏🥬",
    category: "6",
  },
  {
    id: 5,
    img: "https://i9.ytimg.com/vi_webp/HF2dXaUxVnw/sddefault.webp?v=625334da&sqp=COyh9ZsG&rs=AOn4CLBd1qQXITFKfKZI-wB79cth0rEfQg",
    link: "https://www.youtube.com/embed/HF2dXaUxVnw",
    heading: "ТОП 3 начинки для ВАРЕНИКІВ",
    subheading: "ТІСТО, що не розварюється🥟🥟🥟",
    category: "1, 2",
  },
  {
    id: 4,
    img: "https://i9.ytimg.com/vi_webp/IHL9qLNiceA/maxresdefault.webp?v=624acd51&sqp=COyh9ZsG&rs=AOn4CLD9EFvmF_3T4uJ3nDyDC24xiNCrJA",
    link: "https://www.youtube.com/embed/IHL9qLNiceA",
    heading: "Експрес - ВІДБИВНІ без Смаження на сковороді",
    subheading: "ШВИДКО та ЕКОНОМНО🥩",
    category: "2",
  },
  {
    id: 3,
    img: "https://i9.ytimg.com/vi_webp/6E04A_tvnEw/maxresdefault.webp?v=62430ed6&sqp=COyh9ZsG&rs=AOn4CLABqJyEEKS-xbKQtVfU3asIqp-kug",
    link: "https://www.youtube.com/embed/6E04A_tvnEw",
    heading: "Гречана СМАКОТА з картопляними Кльоцками🥣🥔",
    subheading: "Гречаний суп із кльоцками",
    category: "3",
  },
  {
    id: 2,
    img: "https://i9.ytimg.com/vi/P0_DtB_GXuQ/maxresdefault.jpg?v=620e5bf9&sqp=COyh9ZsG&rs=AOn4CLAy4xEF42gK4TelXvV1S7DLc4twfw",
    link: "https://www.youtube.com/embed/P0_DtB_GXuQ",
    heading: "🍊🍋Цитрусові цукати",
    subheading: "випічка на ВЕЛИКДЕНЬ 🍊🍋",
    category: "5",
  },
  {
    id: 1,
    img: "https://i9.ytimg.com/vi_webp/ZWA_FzCjnI0/maxresdefault.webp?v=6328bddf&sqp=CLCD9ZsG&rs=AOn4CLDi8FQRKpn8CS9XJG-0Rpt-4F2w9Q",
    link: "https://www.youtube.com/embed/ZWA_FzCjnI0",
    heading: "ОБЗОР та ВІДГУК на морозильну камеру Vestfrost CMF144W",
    subheading: "Чесний відгук",
    category: "7",
  },
  {
    id: 19,
    img: new URL("../img/video_buters.jpg", import.meta.url),
    link: "https://www.youtube.com/embed/5pKsJYTyYj0",
    heading: "🔴ТОП 3 незвичайних закусок зі звичайного Оселедця ❗",
    subheading: "ЩОСЬ НОВЕНЬКЕ на святковий стіл🎄 ❗",
    category: "7",
  },

  // {
  //   id: 10,
  //   img: "",
  //   link: "",
  //   heading: "",
  //   subheading: "",
  //   category: "",
  // },
];
